In [ ]:
#To install any python module,we use pip
# !pip install <module name> (Jupyter notebook)

In [2]:
# !pip install numpy

In [3]:
import numpy as np

In [27]:
a = [10, 20, 13, 14, 16]

In [28]:
type(a)

list

In [29]:
a+3

TypeError: can only concatenate list (not "int") to list

In [10]:
# add 3 for all the list elements 
#[13,23,16,17,19]

In [15]:
y=[]
for i in a:
    y.append(i+3)

print(y)

[13, 23, 16, 17, 19]


In [20]:
b = np.array([10, 20, 13, 14, 16])

In [23]:
type(b)

numpy.ndarray

In [25]:
b.ndim

1

In [26]:
b+3  #any operation on numpy array will element wise

array([13, 23, 16, 17, 19])

In [30]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [31]:
np.array([1,2.0,3,4]) # Numpy will do upcast automatically

array([1., 2., 3., 4.])

In [32]:
# 2 - dimensional arrays

In [34]:
x = np.array([[1,2,3],[4,5,6]])

In [35]:
x.ndim

2

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
y = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [37]:
y.ndim

3

In [38]:
y

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
x.shape

(2, 3)

In [41]:
y.shape

(1, 3, 3)

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.arange(10)  # Start, stop, stepsize or end number only (n-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [50]:
np.arange(1,10,3)

array([1, 4, 7])

In [52]:
np.random.rand(10)

array([0.73305683, 0.86467676, 0.86835143, 0.8620144 , 0.75445713,
       0.70069846, 0.11535722, 0.42104845, 0.40543111, 0.5883117 ])

In [54]:
np.random.rand(10)

array([0.325788  , 0.45005069, 0.46066032, 0.54766524, 0.28127768,
       0.31417106, 0.51098486, 0.57427735, 0.74225082, 0.7153568 ])

In [55]:
np.random.rand(10)

array([0.19452969, 0.42804038, 0.91700963, 0.11276225, 0.96838492,
       0.79950872, 0.42240828, 0.27747017, 0.57132721, 0.44796584])

In [56]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [58]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [59]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [60]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [61]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [62]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [63]:
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
np.eye(3)  # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
y = np.array([[5,10,15],[20,25,20]])

In [67]:
y.shape

(2, 3)

In [68]:
y.size

6

In [70]:
y

array([[ 5, 10, 15],
       [20, 25, 20]])

In [71]:
# Reshape

In [74]:
a = np.array([3,6,9,12])

In [75]:
a.ndim

1

In [76]:
b = np.reshape(a,(2,2))

In [77]:
b.ndim

2

In [78]:
b

array([[ 3,  6],
       [ 9, 12]])

In [79]:
b

array([[ 3,  6],
       [ 9, 12]])

In [80]:
b.flatten()

array([ 3,  6,  9, 12])

In [81]:
a = np.array([[1,2,3],
[4,5,6]])

In [83]:
a           # 2x3 matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a.transpose()  #3x2 matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
a = np.array([1,2,3,4,5,6])

In [87]:
a

array([1, 2, 3, 4, 5, 6])

In [92]:
print(a[1:5:2]) # Start, end, step size (index wise)

[2 4]


In [89]:
lst = [1, 2, 3, 4, 5, 6]

In [91]:
lst[1:5:2]  # Index mode

[2, 4]

In [93]:
a = np.ones((3,3))
b = np.array([2])
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [94]:
a = np.ones((3,3))

In [95]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
b

array([2])

In [97]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [98]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
%timeit a+b

100 ns ± 1.56 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [99]:
a = np.arange(1,6)
b = np.arange(6,11)

In [100]:
a

array([1, 2, 3, 4, 5])

In [101]:
b

array([ 6,  7,  8,  9, 10])

In [102]:
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


In [104]:
a.min()

1

In [105]:
a.max()

5

In [106]:
b.min()

6

In [107]:
b.max()

10

In [119]:
np.sort(a,kind='quicksort')

array([1, 2, 3, 4, 5])