In [1]:
# Linux Module - Subprocess

In [2]:
import subprocess

In [11]:
cmd = subprocess.getoutput("hostname")

In [12]:
cmd

'rhel8-master'

In [13]:
cmd1 = subprocess.getstatusoutput("hostname")

In [14]:
cmd1

(0, 'rhel8-master')

In [15]:
cmd1[0]

0

In [16]:
cmd1[1]

'rhel8-master'

In [17]:
(cmd1[0] == 0)

True

In [19]:
!pip3 install numpy

    100% |████████████████████████████████| 13.4MB 76kB/s eta 0:00:01    17% |█████▊                          | 2.4MB 2.3MB/s eta 0:00:05    28% |█████████                       | 3.8MB 922kB/s eta 0:00:11    34% |███████████                     | 4.6MB 842kB/s eta 0:00:11    39% |████████████▉                   | 5.4MB 1.0MB/s eta 0:00:08    49% |███████████████▊                | 6.6MB 1.0MB/s eta 0:00:07    99% |████████████████████████████████| 13.4MB 427kB/s eta 0:00:01


In [21]:
import numpy as np

In [23]:
a = [1,2,4,5,8,9]
# add +2 for my a
# y = [3,5,6,7,10,11]

In [25]:
a+2

TypeError: can only concatenate list (not "int") to list

In [26]:
a = np.array([1,2,4,5,8,9])

In [27]:
a

array([1, 2, 4, 5, 8, 9])

In [28]:
type(a)

numpy.ndarray

In [29]:
a+2

array([ 3,  4,  6,  7, 10, 11])

In [30]:
a*4

array([ 4,  8, 16, 20, 32, 36])

In [32]:
b = np.array([1,2,4,5,8,9],dtype=np.float32)

In [33]:
b

array([1., 2., 4., 5., 8., 9.], dtype=float32)

In [34]:
np.array([1,2.0,3,4])  # auto upcast

array([1., 2., 3., 4.])

In [35]:
a.ndim

1

In [39]:
c = np.array([[1,2],[3,4]])

In [40]:
c.ndim

2

In [43]:
d = np.array([[[1,2],[3,4],[5,6]]])

In [44]:
d.ndim

3

In [45]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [50]:
np.random.rand(2,3)

array([[0.11895378, 0.44098515, 0.31707296],
       [0.60469151, 0.73236264, 0.55583399]])

In [51]:
np.random.rand(2,3)

array([[0.36149526, 0.86702164, 0.07153658],
       [0.00292756, 0.12240967, 0.63468166]])

In [52]:
np.random.rand(2,3)

array([[0.8926569 , 0.42189436, 0.12474016],
       [0.42568723, 0.76984568, 0.2846861 ]])

In [53]:
np.full((1,1),7)

array([[7]])

In [54]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
np.eye(3)   # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [58]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [61]:
np.arange(5)  # To generate sequene of array numbers

array([0, 1, 2, 3, 4])

In [62]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [63]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [65]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [66]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [68]:
d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [70]:
d.shape

(1, 3, 2)

In [71]:
c

array([[1, 2],
       [3, 4]])

In [72]:
c.shape

(2, 2)

In [73]:
c.size

4

In [74]:
d.size

6

In [75]:
a = np.array([3,6,9,12])

In [76]:
a

array([ 3,  6,  9, 12])

In [77]:
a.shape

(4,)

In [78]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [79]:
a.flatten()

array([ 3,  6,  9, 12])

In [80]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [81]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [82]:
a[::-1]

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [83]:
a[:,-1]

array([ 5, 10])

In [84]:
a = np.arange(10,20,2)

In [85]:
a

array([10, 12, 14, 16, 18])

In [86]:
b = np.array([[2],[2]])

In [87]:
b

array([[2],
       [2]])

In [88]:
a.shape

(5,)

In [89]:
b.shape

(2, 1)

In [90]:
a+b

array([[12, 14, 16, 18, 20],
       [12, 14, 16, 18, 20]])

In [91]:
a

array([10, 12, 14, 16, 18])

In [92]:
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [ 5  7  9 11 13]
Multiply : [50 60 70 80 90]
Divide : [2.  2.4 2.8 3.2 3.6]
Power : [100 144 196 256 324]
Remainder : [0 2 4 1 3]


In [93]:
np.mean(a)

14.0

In [96]:
np.min(a)

10

In [97]:
np.max(a)

18

In [98]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a, kind='quicksort')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])