In [2]:
import datetime

In [6]:
x = datetime.datetime.now()

In [7]:
print(x)

2022-11-04 09:42:55.576951


In [8]:
x.year

2022

In [9]:
x.month

11

In [11]:
x.st

datetime.date(2022, 11, 4)

In [12]:
print(x.strftime("%A"))

Friday


In [13]:
print(x.strftime("%x"))

11/04/22


In [14]:
print(x.strftime("%X"))

09:42:55


In [17]:
print(x.strftime("%x_%X"))

11/04/22_09:42:55


In [22]:
print(x.strftime("%d-%m-%Y_%X_%p"))

04-11-2022_09:42:55_AM


In [25]:
y="install_log_"+x.strftime("%d-%m-%Y_%X_%p")

In [26]:
y

'install_log_04-11-2022_09:42:55_AM'

In [44]:
from datetime import datetime
date_str='09/19/18 13:55:26'
# print(type(date_str))
z=datetime.strptime(date_str, '%m/%d/%y %H:%M:%S')
print(z)

2018-09-19 13:55:26


In [45]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [48]:
import numpy as np

In [53]:
# mean ?? average of given numbers
num = (1,2,5,6,2,1)
# avg = sum(num)/total num
avg = (1+2+5+6+2+1)/6
print(avg)

2.8333333333333335


In [55]:
np.mean(num)

2.8333333333333335

In [64]:
from scipy import stats
a = np.array(num)
print(stats.mode(a))

ModeResult(mode=array([1]), count=array([2]))


<ipython-input-64-33ea8ebe77c8>:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(stats.mode(a))


In [1]:
import numpy as np
print(np.array([1,2,3,4]))

[1 2 3 4]


In [3]:
print(np.array([1,2,3,4],dtype=np.float32))

[1. 2. 3. 4.]


In [4]:
np.array([1,2.4,3,4])

array([1. , 2.4, 3. , 4. ])

In [6]:
np.array([1.0,2.0,3.0,4.0])

array([1., 2., 3., 4.])

In [7]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.ones(6,dtype=np.int32)

array([1, 1, 1, 1, 1, 1])

In [22]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [23]:
np.random.rand(2,3)

array([[0.15403402, 0.81270971, 0.4719541 ],
       [0.2481259 , 0.35498246, 0.74333992]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [26]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [34]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [35]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])